# Generated by Django 2.2.1 on 2019-06-02 23:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('aplaylist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albumplaylist',
            name='name',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='albumplaylist',
            unique_together={('user', 'name')},
        ),
    ]
